# Generated by Django 3.1.5 on 2021-01-04 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charts',
            fields=[
                ('charts_id', models.AutoField(primary_key=True, serialize=False)),
                ('charts_name', models.CharField(max_length=100)),
                ('charts_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('radio_id', models.AutoField(primary_key=True, serialize=False)),
                ('radio_name', models.CharField(max_length=100)),
                ('radio_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('album_name', models.CharField(max_length=50)),
                ('album_description', models.TextField(blank=True, null=True)),
                ('album_genre', models.ManyToManyField(to='playlist.Genre')),
                ('album_music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.music')),
            ],
        ),
    ]
