# Generated by Django 3.1.4 on 2021-01-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_album_charts_radio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='Autour_name',
        ),
        migrations.AddField(
            model_name='genre',
            name='date_of_make',
            field=models.CharField(default=8.246742536698004e-05, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='music_name',
            field=models.CharField(default='history', max_length=200),
            preserve_default=False,
        ),
    ]
